# Tên ?ng d?ng
spring.application.name=expense-manager

# Server ch?y c?ng 8080
server.port=8080

# K?t n?i PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_manager
spring.datasource.username=trungtai
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA t? t?o b?ng d?a theo Java class
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=expenseManagerSecretKey2024ChangeThisInProduction
jwt.expiration=86400000
# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trungtai03@gmail.com
spring.mail.password=ujkpgicpihrdjadm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true